version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    expose:
      - '5672'
      - '15672'
    ports:
      - '5672:5672'
      - '15672:15672'

  api:
    build: 
      context: ./api
    restart: always
    expose: 
      - '4000'
    ports:
      - '4000:4000'
    command: 'node dist/index.js'

  processor:
    build:
      context: ./processor
    command: 'node dist/index.js'
